### ISSUE TITLE
what is the license?

### ISSUE THREAD

**Issue by benoitc** [cloudant/ets_lru#1]
Headers only say it's copyrighted to cloudant with no information about the license.

**Comment by kocolosk** [comment]
Ooh, faux pas.  We'll get that sorted, thanks for the note.

**Comment by qrilka** [comment]
@kocolosk 8 months passed and no success on this yet?

**Comment by rnewson** [comment]
I filed https://github.com/cloudant/ets_lru/pull/5 to get this sorted, sorry for the delay.

**Comment by rnewson** [comment]
This project is licensed under the Apache Software License, version 2.
